---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install nodejs, npm"
  become: yes
  apt:
    name:
      - nodejs=13.8
      - "npm"
      - "build-essential"
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive artifacts
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Start app
  become: yes
  shell: |
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
  register: print_result

- name: print message
  debug:
    msg: "{{ print_result.stdout_lines }}"