---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "remove dependencies no longer required"
  become: yes
  apt:
    autoremove: yes
- name: "install nodejs, npm"
  become: yes
  apt:
    name:
      - "nodejs"
      - "npm"
      - "build-essential"
    state: latest
    update_cache: yes
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Creates directory
  become: yes
  file:
    path: ~/project/backend
    state: directory
    mode: '0755'
- name: Unarchive artifacts
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/project/backend/
- name: Start app
  become: yes
  shell: |
    cd ~/project/backend/
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env