---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "remove dependencies no longer required"
  become: yes
  apt:
    autoremove: yes
- name: "install nodejs, npm"
  become: yes
  apt:
    name:
      - "nodejs"
      - "npm"
      - "build-essential"
    state: latest
    update_cache: yes
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present